name: Build APK

on: [push]

jobs:
  Build AAR:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of your repository on the runner.
      - uses: actions/checkout@v3

      # Configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Assemble APK
        run: bash ./gradlew assembleDebug --stacktrace

      # Publish artifacts
      - name: Upload APK
        uses: actions/upload-artifacts@v3
        if: always()
        with:
          name: apk_aar
          path: |
            **/*.apk
            **/*.aark
  Build APK:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of your repository on the runner.
      - uses: actions/checkout@v3

      # Configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Assemble APK
        run: bash ./gradlew assembleDebug --stacktrace

      # Publish artifacts
      - name: Upload APK
        uses: actions/upload-artifacts@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk